
# vim: sts=2 ts=10 expandtab
connection:
  available:
#   ExampleSchemaName: # This corresponds to the php namespace you want to put the connection in
#     vendor: Postgres # or Mysql; loads DatabasePostgres or DatabaseMysql class
#     host: localhost
#     dbname: 
#     user: 
#     password: 
#     port: 5432
#  enabled: [ ExampleSchemaName ] # list your Schema key from above
#  default: ExampleSchemaName
  
static_content:
  exclude_ext:
    - php
    - yml
default_layout: LayoutDefault
route:
  default: Home
  error: Error404

